language: php
php:
  - 7.0
  - 7.1

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - sudo apt-get install beanstalkd
  - composer install
  - vendor/bin/phpcs
  - vendor/bin/phpstan analyse --no-progress -l 6 src tests
