sudo: required

language: php
php:
  - 7.0
  - 7.1

cache:
  directories:
    - $HOME/.composer/cache

install:
  - sudo apt-get update
  - sudo apt-get install --force-yes beanstalkd

before_script:
  - composer install
  - vendor/bin/phpcs
  - vendor/bin/phpstan analyse --no-progress -l 6 -c phpstan.neon src tests
