sudo: required

language: php
php:
  - 7.1
  - 7.2

env:
  - ESB_CONSOLE_PORT=8080 ESB_HTTP_SERVER_PORT=34981 ESB_BEANSTALKD_URL=tcp://127.0.0.1:11300 ES_BASE_URI=http://127.0.0.1:9200

cache:
  directories:
    - $HOME/.composer/cache

services:
  - docker
  - elasticsearch

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.4.1-amd64.deb && sudo dpkg -i --force-confnew elasticsearch-7.4.1-amd64.deb && sudo service elasticsearch restart

install:
  - sudo apt-get update
  - sudo apt-get install beanstalkd

before_script:
  - composer install
  - composer global require maglnet/composer-require-checker && $HOME/.composer/vendor/bin/composer-require-checker --config-file=composer-require-checker.json;
  - vendor/bin/phpcs
  - vendor/bin/phpstan analyse --no-progress -l 6 -c phpstan.neon src tests

after_success:
  - docker run --rm -v $(pwd):/app nyholm/roave-bc-check roave-backwards-compatibility-check:assert-backwards-compatible --from=$(git describe --tags $(git rev-list --tags --max-count=1))
