services:
  _defaults:
    autowire: true

  Webgriffe\Esb\Service\:
    resource: 'src/Service/*'

  Webgriffe\Esb\FlowManager:
    public: true

  Amp\Beanstalk\BeanstalkClient:
    arguments: [ '%beanstalkd%' ]
    shared: false

  Webgriffe\Esb\Service\HttpProducersServer:
    arguments:
      $port: '%http_server_port%'

  esb_logger.stdout_stream:
    class: \Amp\ByteStream\ResourceOutputStream
    arguments: [!php/const:\STDOUT]

  esb_logger.stderr_stream:
    class: \Amp\ByteStream\ResourceOutputStream
    arguments: [!php/const:\STDERR]

  esb_logger.stdout_stream_handler:
    class: \Amp\Log\StreamHandler
    arguments: [ '@esb_logger.stdout_stream', !php/const:Monolog\Logger::DEBUG ]

  esb_logger.stderr_stream_handler:
    class: \Amp\Log\StreamHandler
    arguments: [ '@esb_logger.stderr_stream', !php/const:Monolog\Logger::ERROR ]

  Monolog\Formatter\HtmlFormatter: {}

  Monolog\Handler\NativeMailerHandler:
    class: \Monolog\Handler\NativeMailerHandler
    arguments: [ '%logger_mail_to%', 'Significant event from ESB', '%logger_mail_from%', !php/const:Monolog\Logger::WARNING ]
    calls:
      - method: setFormatter
        arguments:
          - '@Monolog\Formatter\HtmlFormatter'
      - method: setContentType
        arguments:
          - 'text/html'

  Psr\Log\LoggerInterface:
    class: \Monolog\Logger
    arguments: [ 'esb', ['@esb_logger.stdout_stream_handler', '@esb_logger.stderr_stream_handler', '@Monolog\Handler\NativeMailerHandler'] ]
    public: true

  Webgriffe\Esb\DateTimeBuilderInterface:
    class: \Webgriffe\Esb\DateTimeBuilder

  console_logger.file_handler:
    class: \Webgriffe\Esb\FileStreamHandler
    arguments: [ '%console_log_file%' ]

  console_logger:
    class: \Monolog\Logger
    arguments: ['esb_console', ['@console_logger.file_handler']]

  Webgriffe\Esb\Console\Server:
    class: \Webgriffe\Esb\Console\Server
    arguments:
      - '@Amp\Beanstalk\BeanstalkClient'
      -
        port: '%console_port%'
        username: '%console_username%'
        password: '%console_password%'
      - '@console_logger'
    public: true
