services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Webgriffe\Esb\Service\:
    resource: 'src/Service/*'

  Webgriffe\Esb\Service\BeanstalkClientFactory:
    class: \Webgriffe\Esb\Service\BeanstalkClientFactory
    arguments: [ '%beanstalkd%' ]

  Amp\Beanstalk\BeanstalkClient:
    arguments: [ '%beanstalkd%' ]
    shared: false

  Webgriffe\Esb\Service\HttpProducersServer:
    arguments:
      $port: '%http_server_port%'

  Monolog\Handler\StreamHandler:
    class: \Monolog\Handler\StreamHandler
    arguments: [ 'php://stdout', !php/const:Monolog\Logger::DEBUG ]

  Monolog\Handler\ErrorLogHandler:
    class: \Monolog\Handler\ErrorLogHandler
    arguments: [ !php/const:Monolog\Handler\ErrorLogHandler::OPERATING_SYSTEM, !php/const:Monolog\Logger::ERROR ]

  Monolog\Handler\NativeMailerHandler:
    class: \Monolog\Handler\NativeMailerHandler
    arguments: [ '%critical_events_to%', 'Critical event from ESB', '%critical_events_from%', !php/const:Monolog\Logger::CRITICAL ]

  Monolog\Logger:
    class: \Monolog\Logger
    arguments: [ 'esb', ['@Monolog\Handler\StreamHandler', '@Monolog\Handler\ErrorLogHandler', '@Monolog\Handler\NativeMailerHandler'] ]

  Webgriffe\Esb\DateTimeBuilderInterface:
    class: \Webgriffe\Esb\DateTimeBuilder

  Webgriffe\Esb\Console\Server:
    class: \Webgriffe\Esb\Console\Server
    arguments:
      - '@Webgriffe\Esb\Service\BeanstalkClientFactory'
      -
        port: '%console_port%'
        username: '%console_username%'
        password: '%console_password%'
      - '@Monolog\Logger'
