services:

  console.controller.abstract:
    abstract: true
    class: '\Webgriffe\Esb\Console\Controller\AbstractController'
    arguments:
      - '@console.twig'
      - '@Amp\Beanstalk\BeanstalkClient'
      - '@Webgriffe\Esb\FlowManager'
      - '@Webgriffe\AmpElasticsearch\Client'
    public: true

  console.controller.index:
    parent: console.controller.abstract
    class: '\Webgriffe\Esb\Console\Controller\IndexController'

  console.controller.flow:
    parent: console.controller.abstract
    class: '\Webgriffe\Esb\Console\Controller\FlowController'

  console.controller.job:
    parent: console.controller.abstract
    class: '\Webgriffe\Esb\Console\Controller\JobController'

  console.controller.kick:
    parent: console.controller.abstract
    class: '\Webgriffe\Esb\Console\Controller\KickController'

  console.controller.delete:
    parent: console.controller.abstract
    class: '\Webgriffe\Esb\Console\Controller\DeleteController'

